import { describe, expect, it } from 'vitest'

import { groupClasses } from './group-classes'

describe('groupClasses', () => {
  it('orders all regex patterns correctly', () => {
    const result = groupClasses([
      'starting:m-0',
      'open:m-0',
      'ltr:m-0',
      'rtl:m-0',
      'data-[side=top]:m-0',
      'aria-[sort=ascending]:m-0',
      'aria-selected:m-0',
      'aria-required:m-0',
      'aria-readonly:m-0',
      'aria-pressed:m-0',
      'aria-hidden:m-0',
      'aria-expanded:m-0',
      'aria-disabled:m-0',
      'aria-checked:m-0',
      'aria-busy:m-0',
      'not-supports-[display:grid]:m-0',
      'supports-[display:grid]:m-0',
      'print:m-0',
      'noscript:m-0',
      'landscape:m-0',
      'portrait:m-0',
      'any-pointer-none:m-0',
      'any-pointer-coarse:m-0',
      'any-pointer-fine:m-0',
      'pointer-none:m-0',
      'pointer-coarse:m-0',
      'pointer-fine:m-0',
      'inverted-colors:m-0',
      'forced-colors:m-0',
      'contrast-less:m-0',
      'contrast-more:m-0',
      'motion-reduce:m-0',
      'motion-safe:m-0',
      '@max-[96rem]:m-0',
      '@max-7xl:m-0',
      '@max-6xl:m-0',
      '@max-5xl:m-0',
      '@max-4xl:m-0',
      '@max-3xl:m-0',
      '@max-2xl:m-0',
      '@max-xl:m-0',
      '@max-lg:m-0',
      '@max-md:m-0',
      '@max-sm:m-0',
      '@max-xs:m-0',
      '@max-2xs:m-0',
      '@max-3xs:m-0',
      '@min-[96rem]:m-0',
      '@7xl:m-0',
      '@6xl:m-0',
      '@5xl:m-0',
      '@4xl:m-0',
      '@3xl:m-0',
      '@2xl:m-0',
      '@xl:m-0',
      '@lg:m-0',
      '@md:m-0',
      '@sm:m-0',
      '@xs:m-0',
      '@2xs:m-0',
      '@3xs:m-0',
      'max-[120rem]:m-0',
      'max-2xl:m-0',
      'max-xl:m-0',
      'max-lg:m-0',
      'max-md:m-0',
      'max-sm:m-0',
      'min-[120rem]:m-0',
      '2xl:m-0',
      'xl:m-0',
      'lg:m-0',
      'md:m-0',
      'sm:m-0',
      'placeholder:m-0',
      'backdrop:m-0',
      'file:m-0',
      'selection:m-0',
      'marker:m-0',
      'first-line:m-0',
      'first-letter:m-0',
      'after:m-0',
      'before:m-0',
      'read-only:m-0',
      'autofill:m-0',
      'details-content:m-0',
      'placeholder-shown:m-0',
      'out-of-range:m-0',
      'in-range:m-0',
      'user-invalid:m-0',
      'user-valid:m-0',
      'invalid:m-0',
      'valid:m-0',
      'required:m-0',
      'optional:m-0',
      'default:m-0',
      'indeterminate:m-0',
      'checked:m-0',
      'enabled:m-0',
      'disabled:m-0',
      'empty:m-0',
      'nth-last-of-type-2:m-0',
      'nth-of-type-2:m-0',
      'nth-last-2:m-0',
      'nth-2:m-0',
      'only-of-type:m-0',
      'last-of-type:m-0',
      'first-of-type:m-0',
      'even:m-0',
      'odd:m-0',
      'only:m-0',
      'last:m-0',
      'first:m-0',
      'inert:m-0',
      'not-focus:m-0',
      'in-focus:m-0',
      'peer-invalid:m-0',
      'group-hover:m-0',
      'has-checked:m-0',
      '**:m-0',
      '*:m-0',
      'target:m-0',
      'visited:m-0',
      'active:m-0',
      'focus-visible:m-0',
      'focus-within:m-0',
      'focus:m-0',
      'hover:m-0',
      'dark:m-0',
      'bg-white text-black',

      // Same as above but unsorted to test grouping
      'starting:p-0',
      'open:p-0',
      'ltr:p-0',
      'rtl:p-0',
      'data-[side=top]:p-0',
      'aria-[sort=ascending]:p-0',
      'aria-selected:p-0',
      'aria-required:p-0',
      'aria-readonly:p-0',
      'aria-pressed:p-0',
      'aria-hidden:p-0',
      'aria-expanded:p-0',
      'aria-disabled:p-0',
      'aria-checked:p-0',
      'aria-busy:p-0',
      'not-supports-[display:grid]:p-0',
      'supports-[display:grid]:p-0',
      'print:p-0',
      'noscript:p-0',
      'landscape:p-0',
      'portrait:p-0',
      'any-pointer-none:p-0',
      'any-pointer-coarse:p-0',
      'any-pointer-fine:p-0',
      'pointer-none:p-0',
      'pointer-coarse:p-0',
      'pointer-fine:p-0',
      'inverted-colors:p-0',
      'forced-colors:p-0',
      'contrast-less:p-0',
      'contrast-more:p-0',
      'motion-reduce:p-0',
      'motion-safe:p-0',
      '@max-[96rem]:p-0',
      '@max-7xl:p-0',
      '@max-6xl:p-0',
      '@max-5xl:p-0',
      '@max-4xl:p-0',
      '@max-3xl:p-0',
      '@max-2xl:p-0',
      '@max-xl:p-0',
      '@max-lg:p-0',
      '@max-md:p-0',
      '@max-sm:p-0',
      '@max-xs:p-0',
      '@max-2xs:p-0',
      '@max-3xs:p-0',
      '@min-[96rem]:p-0',
      '@7xl:p-0',
      '@6xl:p-0',
      '@5xl:p-0',
      '@4xl:p-0',
      '@3xl:p-0',
      '@2xl:p-0',
      '@xl:p-0',
      '@lg:p-0',
      '@md:p-0',
      '@sm:p-0',
      '@xs:p-0',
      '@2xs:p-0',
      '@3xs:p-0',
      'max-[120rem]:p-0',
      'max-2xl:p-0',
      'max-xl:p-0',
      'max-lg:p-0',
      'max-md:p-0',
      'max-sm:p-0',
      'min-[120rem]:p-0',
      '2xl:p-0',
      'xl:p-0',
      'lg:p-0',
      'md:p-0',
      'sm:p-0',
      'placeholder:p-0',
      'backdrop:p-0',
      'file:p-0',
      'selection:p-0',
      'marker:p-0',
      'first-line:p-0',
      'first-letter:p-0',
      'after:p-0',
      'before:p-0',
      'read-only:p-0',
      'autofill:p-0',
      'details-content:p-0',
      'placeholder-shown:p-0',
      'out-of-range:p-0',
      'in-range:p-0',
      'user-invalid:p-0',
      'user-valid:p-0',
      'invalid:p-0',
      'valid:p-0',
      'required:p-0',
      'optional:p-0',
      'default:p-0',
      'indeterminate:p-0',
      'checked:p-0',
      'enabled:p-0',
      'disabled:p-0',
      'empty:p-0',
      'nth-last-of-type-2:p-0',
      'nth-of-type-2:p-0',
      'nth-last-2:p-0',
      'nth-2:p-0',
      'only-of-type:p-0',
      'last-of-type:p-0',
      'first-of-type:p-0',
      'even:p-0',
      'odd:p-0',
      'only:p-0',
      'last:p-0',
      'first:p-0',
      'inert:p-0',
      'not-focus:p-0',
      'in-focus:p-0',
      'peer-invalid:p-0',
      'group-hover:p-0',
      'has-checked:p-0',
      '**:p-0',
      '*:p-0',
      'target:p-0',
      'visited:p-0',
      'active:p-0',
      'focus-visible:p-0',
      'focus-within:p-0',
      'focus:p-0',
      'hover:p-0',
      'dark:p-0',
      'flex block'
    ])

    expect(result).toEqual([
      'bg-white text-black flex block',
      'dark:m-0 dark:p-0',
      'hover:m-0 hover:p-0',
      'focus:m-0 focus:p-0',
      'focus-within:m-0 focus-within:p-0',
      'focus-visible:m-0 focus-visible:p-0',
      'active:m-0 active:p-0',
      'visited:m-0 visited:p-0',
      'target:m-0 target:p-0',
      '*:m-0 *:p-0',
      '**:m-0 **:p-0',
      'has-checked:m-0 has-checked:p-0',
      'group-hover:m-0 group-hover:p-0',
      'peer-invalid:m-0 peer-invalid:p-0',
      'in-focus:m-0 in-focus:p-0',
      'in-range:m-0 in-range:p-0',
      'not-focus:m-0 not-focus:p-0',
      'not-supports-[display:grid]:m-0 not-supports-[display:grid]:p-0',
      'inert:m-0 inert:p-0',
      'first:m-0 first:p-0',
      'last:m-0 last:p-0',
      'only:m-0 only:p-0',
      'odd:m-0 odd:p-0',
      'even:m-0 even:p-0',
      'first-of-type:m-0 first-of-type:p-0',
      'last-of-type:m-0 last-of-type:p-0',
      'only-of-type:m-0 only-of-type:p-0',
      'nth-2:m-0 nth-2:p-0',
      'nth-last-2:m-0 nth-last-2:p-0',
      'nth-last-of-type-2:m-0 nth-last-of-type-2:p-0',
      'nth-of-type-2:m-0 nth-of-type-2:p-0',
      'empty:m-0 empty:p-0',
      'disabled:m-0 disabled:p-0',
      'enabled:m-0 enabled:p-0',
      'checked:m-0 checked:p-0',
      'indeterminate:m-0 indeterminate:p-0',
      'default:m-0 default:p-0',
      'optional:m-0 optional:p-0',
      'required:m-0 required:p-0',
      'valid:m-0 valid:p-0',
      'invalid:m-0 invalid:p-0',
      'user-valid:m-0 user-valid:p-0',
      'user-invalid:m-0 user-invalid:p-0',
      'out-of-range:m-0 out-of-range:p-0',
      'placeholder-shown:m-0 placeholder-shown:p-0',
      'details-content:m-0 details-content:p-0',
      'autofill:m-0 autofill:p-0',
      'read-only:m-0 read-only:p-0',
      'before:m-0 before:p-0',
      'after:m-0 after:p-0',
      'first-letter:m-0 first-letter:p-0',
      'first-line:m-0 first-line:p-0',
      'marker:m-0 marker:p-0',
      'selection:m-0 selection:p-0',
      'file:m-0 file:p-0',
      'backdrop:m-0 backdrop:p-0',
      'placeholder:m-0 placeholder:p-0',
      'sm:m-0 sm:p-0',
      'md:m-0 md:p-0',
      'lg:m-0 lg:p-0',
      'xl:m-0 xl:p-0',
      '2xl:m-0 2xl:p-0',
      'min-[120rem]:m-0 min-[120rem]:p-0',
      'max-sm:m-0 max-sm:p-0',
      'max-md:m-0 max-md:p-0',
      'max-lg:m-0 max-lg:p-0',
      'max-xl:m-0 max-xl:p-0',
      'max-2xl:m-0 max-2xl:p-0',
      'max-[120rem]:m-0 max-[120rem]:p-0',
      '@3xs:m-0 @3xs:p-0',
      '@2xs:m-0 @2xs:p-0',
      '@xs:m-0 @xs:p-0',
      '@sm:m-0 @sm:p-0',
      '@md:m-0 @md:p-0',
      '@lg:m-0 @lg:p-0',
      '@xl:m-0 @xl:p-0',
      '@2xl:m-0 @2xl:p-0',
      '@3xl:m-0 @3xl:p-0',
      '@4xl:m-0 @4xl:p-0',
      '@5xl:m-0 @5xl:p-0',
      '@6xl:m-0 @6xl:p-0',
      '@7xl:m-0 @7xl:p-0',
      '@min-[96rem]:m-0 @min-[96rem]:p-0',
      '@max-3xs:m-0 @max-3xs:p-0',
      '@max-2xs:m-0 @max-2xs:p-0',
      '@max-xs:m-0 @max-xs:p-0',
      '@max-sm:m-0 @max-sm:p-0',
      '@max-md:m-0 @max-md:p-0',
      '@max-lg:m-0 @max-lg:p-0',
      '@max-xl:m-0 @max-xl:p-0',
      '@max-2xl:m-0 @max-2xl:p-0',
      '@max-3xl:m-0 @max-3xl:p-0',
      '@max-4xl:m-0 @max-4xl:p-0',
      '@max-5xl:m-0 @max-5xl:p-0',
      '@max-6xl:m-0 @max-6xl:p-0',
      '@max-7xl:m-0 @max-7xl:p-0',
      '@max-[96rem]:m-0 @max-[96rem]:p-0',
      'motion-safe:m-0 motion-safe:p-0',
      'motion-reduce:m-0 motion-reduce:p-0',
      'contrast-more:m-0 contrast-more:p-0',
      'contrast-less:m-0 contrast-less:p-0',
      'forced-colors:m-0 forced-colors:p-0',
      'inverted-colors:m-0 inverted-colors:p-0',
      'pointer-fine:m-0 pointer-fine:p-0',
      'pointer-coarse:m-0 pointer-coarse:p-0',
      'pointer-none:m-0 pointer-none:p-0',
      'any-pointer-fine:m-0 any-pointer-fine:p-0',
      'any-pointer-coarse:m-0 any-pointer-coarse:p-0',
      'any-pointer-none:m-0 any-pointer-none:p-0',
      'portrait:m-0 portrait:p-0',
      'landscape:m-0 landscape:p-0',
      'noscript:m-0 noscript:p-0',
      'print:m-0 print:p-0',
      'supports-[display:grid]:m-0 supports-[display:grid]:p-0',
      'aria-busy:m-0 aria-busy:p-0',
      'aria-checked:m-0 aria-checked:p-0',
      'aria-disabled:m-0 aria-disabled:p-0',
      'aria-expanded:m-0 aria-expanded:p-0',
      'aria-hidden:m-0 aria-hidden:p-0',
      'aria-pressed:m-0 aria-pressed:p-0',
      'aria-readonly:m-0 aria-readonly:p-0',
      'aria-required:m-0 aria-required:p-0',
      'aria-selected:m-0 aria-selected:p-0',
      'aria-[sort=ascending]:m-0 aria-[sort=ascending]:p-0',
      'data-[side=top]:m-0 data-[side=top]:p-0',
      'rtl:m-0 rtl:p-0',
      'ltr:m-0 ltr:p-0',
      'open:m-0 open:p-0',
      'starting:m-0 starting:p-0'
    ])
  })

  it('handles wildcard variants', () => {
    const result = groupClasses([
      'data-[state=inactive]:bg-gray-500',
      'data-[state=active]:bg-blue-500',
      'data-selected:bg-green-500',
      'aria-[sort=descending]:bg-red-500',
      'aria-[sort=ascending]:bg-yellow-500',
      'aria-hidden:bg-red-500',
      'not-supports-[display:grid]:bg-pink-500',
      'not-supports-[display:flex]:bg-purple-500',
      'not-supports-backdrop-filter:bg-black',
      'supports-[display:grid]:bg-gray-100',
      'supports-[display:flex]:bg-white',
      'supports-backdrop-filter:bg-gray-200',
      '@max-[960px]:p-4',
      '@max-[475px]:p-2',
      '@min-[960px]:p-6',
      '@min-[475px]:p-3',
      'max-[960px]:text-sm',
      'max-[475px]:text-xs',
      'min-[960px]:text-lg',
      'min-[475px]:text-base',
      'nth-last-of-type-3:bg-red-200',
      'nth-last-of-type-2:bg-red-300',
      'nth-of-type-3:bg-green-300',
      'nth-of-type-2:bg-green-200',
      'nth-last-3:bg-blue-200',
      'nth-last-2:bg-blue-300',
      'nth-3:bg-yellow-200',
      'nth-2:bg-yellow-300',
      'not-[svg]:opacity-100',
      'not-focus:bg-gray-700',
      'in-[svg]:opacity-50',
      'in-focus:bg-gray-900',
      'peer-[.is-dirty]:bg-red-500',
      'peer-required:bg-green-500',
      'group-[.is-published]:bg-blue-500',
      'group-hover:bg-yellow-500',
      'has-[svg]:bg-purple-500',
      'has-checked:bg-pink-500'
    ])

    expect(result).toEqual([
      'has-checked:bg-pink-500',
      'has-[svg]:bg-purple-500',
      'group-hover:bg-yellow-500',
      'group-[.is-published]:bg-blue-500',
      'peer-required:bg-green-500',
      'peer-[.is-dirty]:bg-red-500',
      'in-focus:bg-gray-900',
      'in-[svg]:opacity-50',
      'not-focus:bg-gray-700',
      'not-supports-backdrop-filter:bg-black',
      'not-[svg]:opacity-100',
      'not-supports-[display:flex]:bg-purple-500',
      'not-supports-[display:grid]:bg-pink-500',
      'nth-2:bg-yellow-300',
      'nth-3:bg-yellow-200',
      'nth-last-2:bg-blue-300',
      'nth-last-3:bg-blue-200',
      'nth-last-of-type-2:bg-red-300',
      'nth-last-of-type-3:bg-red-200',
      'nth-of-type-2:bg-green-200',
      'nth-of-type-3:bg-green-300',
      'min-[475px]:text-base',
      'min-[960px]:text-lg',
      'max-[475px]:text-xs',
      'max-[960px]:text-sm',
      '@min-[475px]:p-3',
      '@min-[960px]:p-6',
      '@max-[475px]:p-2',
      '@max-[960px]:p-4',
      'supports-backdrop-filter:bg-gray-200',
      'supports-[display:flex]:bg-white',
      'supports-[display:grid]:bg-gray-100',
      'aria-hidden:bg-red-500',
      'aria-[sort=ascending]:bg-yellow-500',
      'aria-[sort=descending]:bg-red-500',
      'data-selected:bg-green-500',
      'data-[state=active]:bg-blue-500',
      'data-[state=inactive]:bg-gray-500'
    ])
  })
})
